{ lib, pkgs, ... }: {
  # Headless server: disable desktop services from common
  services.avahi.enable = false;
  services.tor.enable = false;
  hardware.flipperzero.enable = false;
  environment.sessionVariables.QT_QPA_PLATFORM = lib.mkForce "";

  sops = {
    defaultSopsFile = ../../secrets.yaml;

    age = {
      # This will automatically import SSH keys as age keys
      sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
      # This is using an age key that is expected to already be in the filesystem
      keyFile = "/var/lib/sops-nix/key.txt";
      # This will generate a new key if the key specified above does not exist
      generateKey = true;
    };

    secrets."tokens/services/forgejo/edge-runner" = { };
  };

  services = {
    tailscale.enable = true;

    openssh = {
      settings.PermitRootLogin = "prohibit-password";
    };

    caddy = {
      enable = true;

      package = pkgs.caddy.withPlugins {
        plugins = [ "github.com/corazawaf/coraza-caddy/v2@v2.6.1" ];
        hash = "sha256-a1KAbgGB6CquZT85JE7SFdYX4DaoYQelUZpXZ74YUoU=";
      };

      globalConfig = ''
        order coraza_waf first
      '';

      extraConfig = ''
        import /etc/caddy/cloudflare-trusted.caddy

        (waf) {
          coraza_waf {
            load_owasp_crs
            directives `
              Include @coraza.conf-recommended
              Include @crs-setup.conf.example
              Include @owasp_crs/*.conf
              SecRuleEngine On
            `
          }
        }

        (default_robots) {
          @robots path /robots.txt

          handle @robots {
            header Content-Type text/plain
            respond <<EOF
            User-agent: *
            Disallow: /
            EOF 200
          }
        }
      '';
    };

    # Logs get big AF and contabo only gives us like 100 gigs at this tier.
    journald.extraConfig = ''
      SystemMaxUse=2G
      SystemKeepFree=5G
      MaxRetentionSec=1month
    '';
  };

  systemd.tmpfiles.rules = [
    "d /etc/caddy 0755 root root -"
  ];

  systemd.services.update-cloudflare-ips = {
    description = "Update Cloudflare trusted proxy IPs for Caddy";
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];

    path = with pkgs; [
      curl
      coreutils
      gnused
      systemd
    ];

    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };

    script = ''
      set -euo pipefail

      DEST="/etc/caddy/cloudflare-trusted.caddy"
      TMP="''${DEST}.tmp"

      echo "# Auto-generated by update-cloudflare-ips.service" > "$TMP"
      echo "(cloudflare_trusted) {" >> "$TMP"
      echo -n "  trusted_proxies " >> "$TMP"

      # Fetch official Cloudflare IPv4 and IPv6 lists
      IPV4=$(curl -fsSL https://www.cloudflare.com/ips-v4)
      IPV6=$(curl -fsSL https://www.cloudflare.com/ips-v6)

      # Join IPs into a single space-separated line
      echo "$IPV4 $IPV6" | tr '\n' ' ' | sed 's/ \+/ /g' >> "$TMP"
      echo "" >> "$TMP"
      echo "}" >> "$TMP"

      # Atomic move to prevent partial reads by Caddy
      mv "$TMP" "$DEST"
      chmod 0644 "$DEST"

      # Reload Caddy only if the service is currently running
      if systemctl is-active --quiet caddy.service; then
        systemctl reload caddy.service
      fi
    '';
  };

  # 3. Systemd Timer (runs daily and 5 minutes after boot)
  systemd.timers.update-cloudflare-ips = {
    description = "Daily update of Cloudflare trusted proxy IPs";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "5min";
      OnCalendar = "daily";
      Persistent = true;
      RandomizedDelaySec = "10min";
    };
  };

  virtualisation = {
    podman = {
      enable = true;
      dockerSocket.enable = true;
      dockerCompat = true;
      defaultNetwork.settings.dns_enabled = true;
    };

    oci-containers.containers = {
      # Declaratively run lithium.
      #lithium = {
      #  image = "denoland/deno:alpine"; # or your custom registry image
      #  cmd = [ "run" "--allow-net" "--allow-env" "main.ts" ];
      #  volumes = [
      #    "/var/lib/discord-bot:/app"
      #  ];
      #  workdir = "/app";
      #  environmentFiles = [
      #    "/var/secrets/discord-bot.env"
      #  ];
      #  autoStart = true;
      #};
    };
  };
}
